<?php
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/sys/autonomic.inc");
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/eyes/eyes.inc");
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/touch/touch.inc");
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/other/heat.inc");
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/ears/ears.inc");
include("/home/adminbrad/ai/nervous/NervousSystem/src/spine/mouth/mouth.inc");

?>